---
version: "3.9"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.2.2
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    volumes:
      - config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.heimdall-secure.entrypoints=websecure"
      - "traefik.http.routers.heimdall-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.heimdall-secure.tls=true"
      - "traefik.http.routers.firefly.service=heimdall"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
networks:
  default:
    external: true
    name: proxy
volumes:
   config:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/heimdall/config
      o: bind
