---
version: "3.9"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2021.11
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 81:80/tcp
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      SERVERIP: ${IP_ADDRESS}
    volumes:
      - ./custom.list:/etc/pihole/custom.list
      - pihole_etc-pihole/:/etc/pihole/
      - pihole_etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 10.2.0.100
  wireguard:
    depends_on: [pihole, duckdns]
    image: lscr.io/linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    ports:
      - ${WIREGUARD_SERVERPORT}:51820/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVERURL=${DUCKDNS_DOMAIN}
      - SERVERPORT=${WIREGUARD_SERVERPORT}
      - PEERS=1 
      - PEERDNS=10.2.0.100
      - INTERNAL_SUBNET=10.13.13.0 
      - ALLOWEDIPS=0.0.0.0/0 
    volumes:
      - wireguard_config:/config
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 10.2.0.200    
  duckdns:
    image: lscr.io/linuxserver/duckdns:4a111dc9-ls90
    container_name: duckdns
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
    networks:
      network:
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
volumes:
   wireguard_config:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/wireguard/config
      o: bind
   pihole_etc-pihole:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/pihole/etc-pihole
      o: bind
   pihole_etc-dnsmasq.d:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/pihole/etc-dnsmasq.d
      o: bind
